---

- name: download client binary
  get_url:
    url: "{{ minio_client.download_url }}"
    checksum: "sha256:{{ minio_download_checksums }}"
    dest: "{{ minio_binary_dir }}/minio-client"
    owner: "root"
    group: "root"
    mode: 0755
